#!/bin/sh

set -eu

export LC_ALL=C.UTF-8

ret=0
script -qfec "{{ CMD }} --mode={{ MODE }} --variant=apt {{ DIST }} - {{ MIRROR }}" /dev/null || ret=$?
if [ "$ret" = 0 ]; then
	echo expected failure but got exit $ret >&2
	exit 1
fi
